# -*- coding: utf-8 -*-
"""health_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXoTLKMOS90StgyVZK_gnDr1UuwiL1IX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

st.title("Healthcare Patient Volume Forecasting")

uploaded_file = st.file_uploader(
    "Upload healthcare operations CSV",
    type=["csv"]
)

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
else:
    st.info("Please upload the healthcare operations CSV file to begin.")
    st.stop()
df.head()

df.shape

df.info()

df.describe()

df.hist(figsize=(18,12))
import matplotlib.pyplot as plt
plt.show()

"""timeseries forecasting begin"""

df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values("Date")

df = df.set_index("Date")

ts = df["Patient_Volume"]

print(ts.head())
print(ts.tail())
print(ts.isna().sum())

plt.figure(figsize=(15,5))

plt.plot(ts)

plt.title("Daily Patient Volume")
plt.xlabel("Date")
plt.ylabel("Patient Volume")

plt.show()

train_size = int(len(ts) * 0.80)

train = ts.iloc[:train_size]
test = ts.iloc[train_size:]

print("Train:", len(train))
print("Test:", len(test))

naive_forecast = pd.Series(
    train.iloc[-1],
    index=test.index
)

from sklearn.metrics import mean_absolute_error, mean_squared_error

naive_mae = mean_absolute_error(test, naive_forecast)

naive_rmse = np.sqrt(
    mean_squared_error(test, naive_forecast)
)

naive_mape = np.mean(
    np.abs((test - naive_forecast) / test)
) * 100

print("Naive MAE:", naive_mae)
print("Naive RMSE:", naive_rmse)
print("Naive MAPE:", naive_mape)

seasonal_values = np.resize(
    train.iloc[-7:].values,
    len(test)
)

seasonal_forecast = pd.Series(
    seasonal_values,
    index=test.index
)

seasonal_values = np.resize(
    train.iloc[-7:].values,
    len(test)
)

seasonal_forecast = pd.Series(
    seasonal_values,
    index=test.index
)

seasonal_naive_mae = mean_absolute_error(test, seasonal_forecast)

seasonal_naive_rmse = np.sqrt(
    mean_squared_error(test, seasonal_forecast)
)

seasonal_naive_mape = np.mean(
    np.abs((test - seasonal_forecast) / test)
) * 100

print("Seasonal Naive MAE:", seasonal_naive_mae)
print("Seasonal Naive RMSE:", seasonal_naive_rmse)
print("Seasonal Naive MAPE:", seasonal_naive_mape)

plt.figure(figsize=(15,5))

plt.plot(test.index, test, label="Actual")
plt.plot(test.index, naive_forecast, label="Naive")
plt.plot(test.index, seasonal_forecast, label="Seasonal Naive")

plt.title("Actual vs Baseline Forecasts")
plt.xlabel("Date")
plt.ylabel("Patient Volume")

plt.legend()
plt.show()

"""arima"""

from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Fit ARIMA model
arima_model = ARIMA(train, order=(1,1,1))
arima_fit = arima_model.fit()

# Forecast for test period
arima_forecast = arima_fit.forecast(steps=len(test))

# Convert to Series with test index
arima_forecast = pd.Series(
    arima_forecast,
    index=test.index
)

# Evaluation
arima_mae = mean_absolute_error(test, arima_forecast)
arima_rmse = np.sqrt(mean_squared_error(test, arima_forecast))
arima_mape = np.mean(
    np.abs((test - arima_forecast) / test)
) * 100

print("ARIMA Performance")
print("------------------")
print(f"MAE  : {arima_mae:.2f}")
print(f"RMSE : {arima_rmse:.2f}")
print(f"MAPE : {arima_mape:.2f}%")

plt.figure(figsize=(15,6))

plt.plot(test.index, test,
         label='Actual')

plt.plot(test.index, arima_forecast,
         label='ARIMA Forecast')

plt.title('Actual vs ARIMA Forecast')
plt.xlabel('Date')
plt.ylabel('Patient Volume')
plt.legend()
plt.grid(alpha=0.3)

plt.show()

"""sarima"""

from statsmodels.tsa.statespace.sarimax import SARIMAX

# Fit SARIMA model
sarima_model = SARIMAX(
    train,
    order=(1,1,1),
    seasonal_order=(1,1,1,7),
    enforce_stationarity=False,
    enforce_invertibility=False
)

sarima_fit = sarima_model.fit(disp=False)

# Forecast
sarima_forecast = sarima_fit.forecast(
    steps=len(test)
)

sarima_forecast = pd.Series(
    sarima_forecast,
    index=test.index
)

# Evaluation
sarima_mae = mean_absolute_error(test, sarima_forecast)

sarima_rmse = np.sqrt(
    mean_squared_error(test, sarima_forecast)
)

sarima_mape = np.mean(
    np.abs((test - sarima_forecast) / test)
) * 100

print("SARIMA Performance")
print("------------------")
print(f"MAE  : {sarima_mae:.2f}")
print(f"RMSE : {sarima_rmse:.2f}")
print(f"MAPE : {sarima_mape:.2f}%")

plt.figure(figsize=(15,6))

plt.plot(
    test.index,
    test,
    label='Actual'
)

plt.plot(
    test.index,
    sarima_forecast,
    label='SARIMA Forecast'
)

plt.title('Actual vs SARIMA Forecast')
plt.xlabel('Date')
plt.ylabel('Patient Volume')
plt.legend()
plt.grid(alpha=0.3)

plt.show()

"""comparison"""

results = pd.DataFrame({
    'Model': [
        'Naive',
        'Seasonal Naive',
        'ARIMA',
        'SARIMA'
    ],

    'MAE': [
        naive_mae,
        seasonal_naive_mae,
        arima_mae,
        sarima_mae
    ],

    'RMSE': [
        naive_rmse,
        seasonal_naive_rmse,
        arima_rmse,
        sarima_rmse
    ],

    'MAPE (%)': [
        naive_mape,
        seasonal_naive_mape,
        arima_mape,
        sarima_mape
    ]
})

results = results.sort_values(
    by='RMSE'
).reset_index(drop=True)

results

"""visual comparison"""

plt.figure(figsize=(16,7))

plt.plot(
    test.index,
    test,
    label='Actual',
    linewidth=2
)

plt.plot(
    test.index,
    naive_forecast,
    label='Naive'
)

plt.plot(
    test.index,
    seasonal_forecast,
    label='Seasonal Naive'
)

plt.plot(
    test.index,
    arima_forecast,
    label='ARIMA'
)

plt.plot(
    test.index,
    sarima_forecast,
    label='SARIMA'
)

plt.title('Actual vs Forecasting Models')
plt.xlabel('Date')
plt.ylabel('Patient Volume')
plt.legend()

plt.grid(alpha=0.3)

plt.show()

best_model = results.loc[
    results['RMSE'].idxmin()
]

print("Best Model:")
print(best_model)

print(
    f"The best-performing model based on RMSE is "
    f"{best_model['Model']}."
)

import matplotlib.pyplot as plt

sarima_fit.plot_diagnostics(figsize=(15,10))

plt.tight_layout()
plt.show()

from statsmodels.stats.diagnostic import acorr_ljungbox

ljung_box = acorr_ljungbox(
    sarima_fit.resid,
    lags=[7, 14, 21],
    return_df=True
)

ljung_box

from statsmodels.tsa.stattools import adfuller

adf_result = adfuller(train.dropna())

print("ADF Statistic:", adf_result[0])
print("p-value:", adf_result[1])

if adf_result[1] < 0.05:
    print("Series is stationary.")
else:
    print("Series is non-stationary.")

import warnings
warnings.filterwarnings("ignore")

sarima_orders = [
    ((1,1,1), (1,1,1,7)),
    ((1,1,0), (1,1,1,7)),
    ((0,1,1), (1,1,1,7)),
    ((1,1,1), (0,1,1,7)),
    ((0,1,1), (0,1,1,7))
]

sarima_results = []

for order, seasonal_order in sarima_orders:

    try:

        model = SARIMAX(
            train,
            order=order,
            seasonal_order=seasonal_order,
            enforce_stationarity=False,
            enforce_invertibility=False
        )

        fitted = model.fit(disp=False)

        forecast = fitted.forecast(
            steps=len(test)
        )

        mae = mean_absolute_error(
            test,
            forecast
        )

        rmse = np.sqrt(
            mean_squared_error(
                test,
                forecast
            )
        )

        mape = np.mean(
            np.abs(
                (test - forecast) / test
            )
        ) * 100

        sarima_results.append({
            'Order': order,
            'Seasonal Order': seasonal_order,
            'MAE': mae,
            'RMSE': rmse,
            'MAPE (%)': mape
        })

    except Exception as e:
        print("Model failed:", order, seasonal_order)

sarima_results_df = pd.DataFrame(
    sarima_results
)

sarima_results_df.sort_values(
    'RMSE'
).reset_index(drop=True)

best_sarima = sarima_results_df.loc[
    sarima_results_df['RMSE'].idxmin()
]

print("Best SARIMA Model")
print("------------------")
print(best_sarima)

best_order = best_sarima['Order']
best_seasonal_order = best_sarima['Seasonal Order']

print("Best Order:", best_order)
print("Best Seasonal Order:", best_seasonal_order)

final_sarima = SARIMAX(
    train,
    order=best_order,
    seasonal_order=best_seasonal_order,
    enforce_stationarity=False,
    enforce_invertibility=False
)

final_sarima_fit = final_sarima.fit(
    disp=False
)

final_forecast = final_sarima_fit.forecast(
    steps=len(test)
)

final_forecast = pd.Series(
    final_forecast,
    index=test.index
)

final_mae = mean_absolute_error(
    test,
    final_forecast
)

final_rmse = np.sqrt(
    mean_squared_error(
        test,
        final_forecast
    )
)

final_mape = np.mean(
    np.abs(
        (test - final_forecast) / test
    )
) * 100

print("FINAL SARIMA PERFORMANCE")
print("-------------------------")
print(f"MAE  : {final_mae:.2f}")
print(f"RMSE : {final_rmse:.2f}")
print(f"MAPE : {final_mape:.2f}%")

plt.figure(figsize=(16,7))

plt.plot(
    test.index,
    test,
    label='Actual',
    linewidth=2
)

plt.plot(
    test.index,
    final_forecast,
    label='Final SARIMA Forecast',
    linewidth=2
)

plt.title(
    'Actual vs Final SARIMA Forecast'
)

plt.xlabel('Date')
plt.ylabel('Patient Volume')

plt.legend()
plt.grid(alpha=0.3)

plt.show()

"""RESOLVING LONG HORIZON FORECAST ISSUES TUNING SARIMA"""

# ==========================================
# STEP 1: Check Final SARIMA Forecast
# ==========================================

plt.figure(figsize=(16,7))

plt.plot(
    test.index,
    test,
    label="Actual",
    linewidth=2
)

plt.plot(
    test.index,
    final_forecast,
    label="SARIMA Forecast",
    linewidth=2
)

# Mark where forecast starts
plt.axvline(
    test.index[0],
    linestyle="--",
    label="Forecast Start"
)

plt.title("Actual vs SARIMA Forecast")
plt.xlabel("Date")
plt.ylabel("Patient Volume")

plt.legend()
plt.grid(alpha=0.3)

plt.show()

# Show first and last 10 forecast values

comparison = pd.DataFrame({
    "Actual": test,
    "SARIMA_Forecast": final_forecast
})

print("FIRST 10 DAYS")
st.dataframe(comparison.tail(10))

print("\nLAST 10 DAYS")
st.dataframe(comparison.tail(10))

# ==========================================
# STEP 2: SARIMA RESIDUAL DIAGNOSTICS
# ==========================================

from statsmodels.stats.diagnostic import acorr_ljungbox
import matplotlib.pyplot as plt

# Get residuals
residuals = final_sarima_fit.resid.dropna()

# Residual plot
plt.figure(figsize=(15, 5))
plt.plot(residuals)
plt.title("SARIMA Residuals")
plt.xlabel("Date")
plt.ylabel("Residual")
plt.grid(alpha=0.3)
plt.show()

# Residual histogram
plt.figure(figsize=(10, 5))
plt.hist(residuals, bins=30)
plt.title("Distribution of SARIMA Residuals")
plt.xlabel("Residual")
plt.ylabel("Frequency")
plt.grid(alpha=0.3)
plt.show()

# Ljung-Box test
ljung_box = acorr_ljungbox(
    residuals,
    lags=[7, 14, 21, 30],
    return_df=True
)

print("Ljung-Box Test:")
st.write(ljung_box)

from statsmodels.stats.diagnostic import acorr_ljungbox

residuals = final_sarima_fit.resid.dropna()

ljung_box = acorr_ljungbox(
    residuals,
    lags=[7, 14, 21, 30],
    return_df=True
)

print("Ljung-Box Test:")
st.write(ljung_box)

# Compare actual vs SARIMA forecast on the test set

comparison = pd.DataFrame({
    "Actual": test,
    "SARIMA_Forecast": final_forecast
})

# Forecast error
comparison["Error"] = comparison["Actual"] - comparison["SARIMA_Forecast"]
comparison["Absolute_Error"] = comparison["Error"].abs()

print("First 10 predictions:")
st.dataframe(comparison.head(10))

print("Last 10 predictions:")
st.dataframe(comparison.tail(10))

print("\nFinal SARIMA Performance:")
print(f"MAE  : {mean_absolute_error(test, final_forecast):.2f}")
print(f"RMSE : {np.sqrt(mean_squared_error(test, final_forecast)):.2f}")
print(f"MAPE : {np.mean(np.abs((test - final_forecast) / test)) * 100:.2f}%")

# Rolling / Updated SARIMA Forecast
# Model is updated after each actual observation

rolling_predictions = []
current_model = final_sarima_fit

for i in range(len(test)):

    # Forecast the next day
    next_forecast = current_model.forecast(steps=1)
    rolling_predictions.append(next_forecast.iloc[0])

    # Update model with the actual observed value
    current_model = current_model.extend(test.iloc[[i]])

# Convert predictions to Series
rolling_forecast = pd.Series(
    rolling_predictions,
    index=test.index
)

# Evaluate rolling forecast
rolling_mae = mean_absolute_error(test, rolling_forecast)
rolling_rmse = np.sqrt(mean_squared_error(test, rolling_forecast))
rolling_mape = np.mean(
    np.abs((test - rolling_forecast) / test)
) * 100

print("ROLLING SARIMA PERFORMANCE")
print(f"MAE  : {rolling_mae:.2f}")
print(f"RMSE : {rolling_rmse:.2f}")
print(f"MAPE : {rolling_mape:.2f}%")

# Actual vs Rolling SARIMA Forecast

plt.figure(figsize=(15, 6))

plt.plot(test.index, test.values, label="Actual")
plt.plot(test.index, rolling_forecast.values, label="Rolling SARIMA Forecast")

plt.title("Actual vs Rolling SARIMA Forecast")
plt.xlabel("Date")
plt.ylabel("Patient Volume")
plt.legend()
plt.grid(alpha=0.3)

plt.show()

# Final Model Comparison

final_comparison = pd.DataFrame({
    "Model": [
        "Naive",
        "Seasonal Naive",
        "ARIMA",
        "SARIMA",
        "Rolling SARIMA"
    ],
    "MAE": [
        naive_mae,
        seasonal_naive_mae,
        arima_mae,
        sarima_mae,
        rolling_mae
    ],
    "RMSE": [
        naive_rmse,
        seasonal_naive_rmse,
        arima_rmse,
        sarima_rmse,
        rolling_rmse
    ],
    "MAPE (%)": [
        naive_mape,
        seasonal_naive_mape,
        arima_mape,
        sarima_mape,
        rolling_mape
    ]
})

final_comparison = final_comparison.sort_values(
    by="RMSE"
).reset_index(drop=True)

st.dataframe(final_comparison)

# ==========================================
# STEP 6: FUTURE FORECAST USING FINAL SARIMA
# ==========================================

# Fit the selected SARIMA model on the complete dataset
final_model_full = SARIMAX(
    ts,
    order=best_order,
    seasonal_order=best_seasonal_order,
    enforce_stationarity=False,
    enforce_invertibility=False
)

final_model_full_fit = final_model_full.fit(disp=False)

# Forecast next 30 days
forecast_steps = 30

future_forecast = final_model_full_fit.forecast(
    steps=forecast_steps
)

# Create future dates
future_dates = pd.date_range(
    start=ts.index[-1] + pd.Timedelta(days=1),
    periods=forecast_steps,
    freq="D"
)

future_forecast = pd.Series(
    future_forecast.values,
    index=future_dates,
    name="Forecast"
)

print("NEXT 30 DAYS FORECAST")
display(future_forecast)

# ==========================================
# FUTURE FORECAST VISUALIZATION
# ==========================================

plt.figure(figsize=(16, 7))

# Last 90 days of actual data
plt.plot(
    ts.tail(90).index,
    ts.tail(90).values,
    label="Actual"
)

# Future forecast
plt.plot(
    future_forecast.index,
    future_forecast.values,
    label="Future SARIMA Forecast",
    linewidth=2
)

plt.axvline(
    ts.index[-1],
    linestyle="--",
    label="Forecast Start"
)

plt.title("Patient Volume: 30-Day Future Forecast")
plt.xlabel("Date")
plt.ylabel("Patient Volume")

plt.legend()
plt.grid(alpha=0.3)

plt.show()

# ==========================================
# REUSABLE SARIMA FORECAST FUNCTION
# ==========================================

from statsmodels.tsa.statespace.sarimax import SARIMAX
import pandas as pd
import numpy as np


def sarima_forecast(data, date_col="Date",
                    target_col="Patient_Volume",
                    forecast_days=30):

    # Copy data
    data = data.copy()

    # Make sure date is datetime
    data[date_col] = pd.to_datetime(data[date_col])

    # Sort by date
    data = data.sort_values(date_col)

    # Create time series
    ts_new = data.set_index(date_col)[target_col].astype(float)

    # Remove missing values
    ts_new = ts_new.dropna()

    # Check minimum history
    if len(ts_new) < 30:
        raise ValueError(
            "At least 30 historical observations are recommended."
        )

    # Fit SARIMA using the selected orders
    model = SARIMAX(
        ts_new,
        order=best_order,
        seasonal_order=best_seasonal_order,
        enforce_stationarity=False,
        enforce_invertibility=False
    )

    fitted_model = model.fit(disp=False)

    # Forecast
    forecast = fitted_model.forecast(
        steps=forecast_days
    )

    # Future dates
    future_dates = pd.date_range(
        start=ts_new.index[-1] + pd.Timedelta(days=1),
        periods=forecast_days,
        freq="D"
    )

    # Create forecast dataframe
    forecast_df = pd.DataFrame({
        "Date": future_dates,
        "Forecast_Patient_Volume": forecast.values
    })

    return forecast_df

new_data = df.reset_index()[["Date", "Patient_Volume"]].copy()

new_forecast = sarima_forecast(
    new_data,
    forecast_days=30
)

display(new_forecast)

# ==========================================
# PLOT NEW DATA + FORECAST
# ==========================================

plt.figure(figsize=(15, 6))

plt.plot(
    new_data["Date"].tail(90),
    new_data["Patient_Volume"].tail(90),
    label="Historical Patient Volume"
)

plt.plot(
    new_forecast["Date"],
    new_forecast["Forecast_Patient_Volume"],
    label="SARIMA Forecast",
    linewidth=2
)

plt.axvline(
    new_data["Date"].max(),
    linestyle="--",
    label="Forecast Start"
)

plt.title("Patient Volume Forecast")
plt.xlabel("Date")
plt.ylabel("Patient Volume")
plt.legend()
plt.grid(alpha=0.3)

plt.show()

# ==========================================
# REUSABLE ROLLING SARIMA FUNCTION
# ==========================================

from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error, mean_squared_error
import pandas as pd
import numpy as np


def rolling_sarima_forecast(
    data,
    date_col="Date",
    target_col="Patient_Volume",
    test_size=0.2,
    order=None,
    seasonal_order=None
):

    # Copy data
    data = data.copy()

    # Prepare dates
    data[date_col] = pd.to_datetime(data[date_col])
    data = data.sort_values(date_col)

    # Create time series
    ts_data = (
        data.set_index(date_col)[target_col]
        .astype(float)
        .dropna()
    )

    # Default to the best SARIMA orders already selected
    if order is None:
        order = best_order

    if seasonal_order is None:
        seasonal_order = best_seasonal_order

    # Train-test split
    split_point = int(len(ts_data) * (1 - test_size))

    train_data = ts_data.iloc[:split_point]
    test_data = ts_data.iloc[split_point:]

    # Initial SARIMA model
    model = SARIMAX(
        train_data,
        order=order,
        seasonal_order=seasonal_order,
        enforce_stationarity=False,
        enforce_invertibility=False
    )

    fitted_model = model.fit(disp=False)

    # Rolling predictions
    predictions = []

    for i in range(len(test_data)):

        # Predict next observation
        forecast = fitted_model.forecast(steps=1)

        predictions.append(forecast.iloc[0])

        # Update model with actual observation
        fitted_model = fitted_model.extend(
            test_data.iloc[[i]]
        )

    # Convert predictions to Series
    predictions = pd.Series(
        predictions,
        index=test_data.index,
        name="Rolling_SARIMA_Forecast"
    )

    # Metrics
    mae = mean_absolute_error(
        test_data,
        predictions
    )

    rmse = np.sqrt(
        mean_squared_error(
            test_data,
            predictions
        )
    )

    mape = np.mean(
        np.abs(
            (test_data - predictions) / test_data
        )
    ) * 100

    # Results dataframe
    results = pd.DataFrame({
        "Actual": test_data,
        "Forecast": predictions,
        "Error": test_data - predictions,
        "Absolute_Error": np.abs(test_data - predictions)
    })

    metrics = {
        "MAE": mae,
        "RMSE": rmse,
        "MAPE (%)": mape
    }

    return results, metrics

future_forecast = sarima_forecast(
    df.reset_index(), # Reset the index so 'Date' is a column again
    date_col="Date",
    target_col="Patient_Volume",
    forecast_days=30 # Use forecast_days for future forecasting
)

# The sarima_forecast function returns a DataFrame directly.
display(future_forecast)

# ==========================================
# FUTURE SARIMA FORECAST VISUALIZATION
# ==========================================

plt.figure(figsize=(15, 6))

plt.plot(
    df.index[-90:], # Corrected to use df.index slicing
    df["Patient_Volume"].tail(90),
    label="Historical Patient Volume"
)

plt.plot(
    future_forecast["Date"],
    future_forecast["Forecast_Patient_Volume"],
    label="SARIMA Forecast", # Updated label
    linewidth=2
)

plt.axvline(
    df.index.max(), # Corrected to use df.index
    linestyle="--",
    label="Forecast Start"
)

plt.title("SARIMA: Future Patient Volume Forecast") # Updated title
plt.xlabel("Date")
plt.ylabel("Patient Volume")
plt.legend()
plt.grid(alpha=0.3)

plt.show()

"""final checks"""

from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np
import pandas as pd

def multi_step_rolling_sarima(
    data,
    date_col="Date",
    target_col="Patient_Volume",
    horizon=30,
    test_size=0.2,
    order=None,
    seasonal_order=None
):

    data = data.copy()
    data[date_col] = pd.to_datetime(data[date_col])
    data = data.sort_values(date_col)

    ts = (
        data.set_index(date_col)[target_col]
        .astype(float)
        .dropna()
    )

    if order is None:
        order = best_order

    if seasonal_order is None:
        seasonal_order = best_seasonal_order

    split_point = int(len(ts) * (1 - test_size))

    train = ts.iloc[:split_point]
    test = ts.iloc[split_point:]

    forecasts = []
    actuals = []
    forecast_dates = []

    # Start points inside the test period
    for start in range(0, len(test), horizon):

        history_end = split_point + start
        history = ts.iloc[:history_end]

        remaining = len(test) - start
        steps = min(horizon, remaining)

        model = SARIMAX(
            history,
            order=order,
            seasonal_order=seasonal_order,
            enforce_stationarity=False,
            enforce_invertibility=False
        )

        fitted = model.fit(disp=False)

        forecast = fitted.forecast(steps=steps)

        actual = test.iloc[start:start + steps]

        forecasts.extend(forecast.values)
        actuals.extend(actual.values)
        forecast_dates.extend(actual.index)

    forecasts = pd.Series(
        forecasts,
        index=forecast_dates,
        name="Forecast"
    )

    actuals = pd.Series(
        actuals,
        index=forecast_dates,
        name="Actual"
    )

    mae = mean_absolute_error(actuals, forecasts)
    rmse = np.sqrt(mean_squared_error(actuals, forecasts))
    mape = np.mean(
        np.abs((actuals - forecasts) / actuals)
    ) * 100

    results = pd.DataFrame({
        "Actual": actuals,
        "Forecast": forecasts
    })

    results["Error"] = results["Actual"] - results["Forecast"]
    results["Absolute_Error"] = np.abs(results["Error"])

    metrics = {
        "MAE": mae,
        "RMSE": rmse,
        "MAPE (%)": mape
    }

    return results, metrics

multi_results, multi_metrics = multi_step_rolling_sarima(
    df.reset_index(), # Reset the index so 'Date' is a column again
    date_col="Date",
    target_col="Patient_Volume",
    horizon=30,
    test_size=0.2
)

print("30-Day Rolling SARIMA Performance")
print("----------------------------------")
print(f"MAE  : {multi_metrics['MAE']:.2f}")
print(f"RMSE : {multi_metrics['RMSE']:.2f}")
print(f"MAPE : {multi_metrics['MAPE (%)']:.2f}%")

import matplotlib.pyplot as plt

plt.figure(figsize=(15, 6))

plt.plot(
    multi_results.index,
    multi_results["Actual"],
    label="Actual"
)

plt.plot(
    multi_results.index,
    multi_results["Forecast"],
    label="30-Day Forecast"
)

plt.title("30-Day Rolling SARIMA Backtest")
plt.xlabel("Date")
plt.ylabel("Patient Volume")
plt.legend()
plt.grid(True)

plt.show()

"""csv validation prior to forecast"""

import pandas as pd
import numpy as np

def validate_forecasting_data(
    data,
    date_col="Date",
    target_col="Patient_Volume",
    min_days=90
):

    df_check = data.copy()
    problems = []
    warnings = []

    # -----------------------------
    # 1. Required columns
    # -----------------------------
    if date_col not in df_check.columns:
        problems.append(f"Missing required column: {date_col}")

    if target_col not in df_check.columns:
        problems.append(f"Missing required column: {target_col}")

    if problems:
        return {
            "valid": False,
            "problems": problems,
            "warnings": warnings
        }

    # -----------------------------
    # 2. Convert Date
    # -----------------------------
    df_check[date_col] = pd.to_datetime(
        df_check[date_col],
        errors="coerce"
    )

    invalid_dates = df_check[date_col].isna().sum()

    if invalid_dates > 0:
        problems.append(
            f"{invalid_dates} invalid or missing dates found."
        )

    # -----------------------------
    # 3. Convert target to numeric
    # -----------------------------
    df_check[target_col] = pd.to_numeric(
        df_check[target_col],
        errors="coerce"
    )

    missing_target = df_check[target_col].isna().sum()

    if missing_target > 0:
        problems.append(
            f"{missing_target} missing/non-numeric "
            f"{target_col} values found."
        )

    # -----------------------------
    # Stop if dates are invalid
    # -----------------------------
    if df_check[date_col].isna().any():
        return {
            "valid": False,
            "problems": problems,
            "warnings": warnings
        }

    # -----------------------------
    # 4. Sort dates
    # -----------------------------
    df_check = df_check.sort_values(date_col)

    # -----------------------------
    # 5. Duplicate dates
    # -----------------------------
    duplicate_dates = df_check[date_col].duplicated().sum()

    if duplicate_dates > 0:
        problems.append(
            f"{duplicate_dates} duplicate dates found."
        )

    # -----------------------------
    # 6. Negative patient volume
    # -----------------------------
    negative_values = (
        df_check[target_col].dropna() < 0
    ).sum()

    if negative_values > 0:
        problems.append(
            f"{negative_values} negative "
            f"{target_col} values found."
        )

    # -----------------------------
    # 7. Number of observations
    # -----------------------------
    n = len(df_check)

    if n < min_days:
        problems.append(
            f"Only {n} observations found. "
            f"At least {min_days} observations are recommended."
        )

    # -----------------------------
    # 8. Date range
    # -----------------------------
    start_date = df_check[date_col].min()
    end_date = df_check[date_col].max()

    # -----------------------------
    # 9. Missing dates
    # -----------------------------
    expected_dates = pd.date_range(
        start=start_date,
        end=end_date,
        freq="D"
    )

    actual_dates = pd.DatetimeIndex(
        df_check[date_col].drop_duplicates()
    )

    missing_dates = expected_dates.difference(actual_dates)

    if len(missing_dates) > 0:
        warnings.append(
            f"{len(missing_dates)} missing calendar dates found."
        )

    # -----------------------------
    # 10. Very low variation
    # -----------------------------
    if df_check[target_col].nunique(dropna=True) <= 1:
        problems.append(
            f"{target_col} has no meaningful variation."
        )

    # -----------------------------
    # Final result
    # -----------------------------
    valid = len(problems) == 0

    return {
        "valid": valid,
        "observations": n,
        "start_date": start_date,
        "end_date": end_date,
        "problems": problems,
        "warnings": warnings
    }

validation = validate_forecasting_data(
    df,
    date_col="Date",
    target_col="Patient_Volume"
)

print("DATA VALIDATION")
print("================")

print("Valid:", validation["valid"])
print("Observations:", validation.get("observations"))
print("Start Date:", validation.get("start_date"))
print("End Date:", validation.get("end_date"))

print("\nProblems:")
if validation["problems"]:
    for p in validation["problems"]:
        print("❌", p)
else:
    print("✅ No critical problems found.")

print("\nWarnings:")
if validation["warnings"]:
    for w in validation["warnings"]:
        print("⚠️", w)
else:
    print("✅ No warnings.")

print("VALIDATION RESULT")
print("=================")

print("Valid:", validation["valid"])

print("\n❌ PROBLEMS:")
for p in validation["problems"]:
    print("-", p)

print("\n⚠️ WARNINGS:")
for w in validation["warnings"]:
    print("-", w)

validation = validate_forecasting_data(
    df.reset_index(),
    date_col="Date",
    target_col="Patient_Volume"
)

print("VALIDATION RESULT")
print("=================")

print("Valid:", validation["valid"])
print("Observations:", validation.get("observations"))
print("Start Date:", validation.get("start_date"))
print("End Date:", validation.get("end_date"))

print("\n❌ PROBLEMS:")
if validation["problems"]:
    for p in validation["problems"]:
        print("-", p)
else:
    print("None")

print("\n⚠️ WARNINGS:")
if validation["warnings"]:
    for w in validation["warnings"]:
        print("-", w)
else:
    print("None")
